# frozen_string_literal: true

source "https://rubygems.org"

gem "falcon"
gem "puma"

gem "rack-ougai", path: "/Users/ed/Development/rack-ougai"

gem "modern", path: File.expand_path("#{__dir__}}/..")
